#!/usr/bin/env python3
"""Ensure editable src layout is importable under macOS + CPython 3.14+.

CPython 3.14's site.py skips .pth files marked UF_HIDDEN on macOS. Hatchling's
editable install writes `_editable_impl_qdata.pth`, which (along with other
.pth files) can get that flag set again by the environment.

Strategy (belt and suspenders):
1. Clear UF_HIDDEN on every *.pth under the active venv site-packages
2. Write a non-underscore `qdata_src.pth` pointing at <repo>/src
3. Write `sitecustomize.py` that prepends <repo>/src — loaded even when all
   .pth files are skipped
"""

from __future__ import annotations

import os
import site
import stat
import sys
from pathlib import Path

_SITECUSTOMIZE = '''\
# Auto-generated by scripts/ensure_import_path.py — do not edit by hand.
import sys
from pathlib import Path

_SRC = Path({src!r})
if _SRC.is_dir():
    p = str(_SRC)
    if p not in sys.path:
        sys.path.insert(0, p)
'''


def _repo_src() -> Path:
    return Path(__file__).resolve().parents[1] / "src"


def _site_packages() -> Path:
    candidates: list[Path] = []
    if hasattr(site, "getsitepackages"):
        candidates.extend(Path(p) for p in site.getsitepackages())
    user = site.getusersitepackages()
    if user:
        candidates.append(Path(user))

    venv_hits = [
        sp
        for sp in candidates
        if sp.is_dir() and (".venv" in sp.parts or "venv" in sp.parts)
    ]
    if venv_hits:
        return venv_hits[0]

    for sp in candidates:
        if sp.is_dir() and "site-packages" in sp.parts:
            return sp
    raise SystemExit("无法定位 site-packages，请用项目 .venv 中的 python 运行本脚本")


def _clear_hidden(path: Path) -> bool:
    if os.name != "posix" or sys.platform != "darwin" or not path.exists():
        return False
    try:
        st = os.lstat(path)
    except OSError:
        return False
    if not (st.st_flags & stat.UF_HIDDEN):
        return False
    os.chflags(path, st.st_flags & ~stat.UF_HIDDEN)
    return True


def _clear_all_pth_hidden(sp: Path) -> list[str]:
    cleared: list[str] = []
    for path in sp.glob("*.pth"):
        if _clear_hidden(path):
            cleared.append(path.name)
    return cleared


def main() -> int:
    src = _repo_src()
    if not (src / "qdata" / "__init__.py").is_file():
        raise SystemExit(f"未找到包入口: {src / 'qdata' / '__init__.py'}")

    sp = _site_packages()

    pth = sp / "qdata_src.pth"
    payload = f"{src}\n"
    pth.write_text(payload, encoding="utf-8")
    print(f"wrote {pth} -> {src}")

    sc = sp / "sitecustomize.py"
    sc.write_text(_SITECUSTOMIZE.format(src=str(src)), encoding="utf-8")
    print(f"wrote {sc}")

    cleared = _clear_all_pth_hidden(sp)
    # sitecustomize / pth 刚写入后也可能被标 hidden（偶发），一并清掉
    for extra in (pth, sc):
        if _clear_hidden(extra) and extra.name not in cleared:
            cleared.append(extra.name)
    if cleared:
        print("cleared UF_HIDDEN:", ", ".join(cleared))

    # Fresh subprocess verification (current process may have started before fixes)
    import subprocess

    probe = (
        "import qdata, qdata.loaders.security_master as m; "
        "print(qdata.__file__); print(m.__file__)"
    )
    proc = subprocess.run(
        [sys.executable, "-c", probe],
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        print(proc.stderr, file=sys.stderr)
        raise SystemExit("验证失败：子进程仍无法 import qdata")
    print("import qdata OK:")
    print(proc.stdout.rstrip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
